### ISSUE TITLE
Errors when initiating the plugin

### ISSUE THREAD

**Issue by christoph-codes** [cmolisee/session-storage-hub#97]
**Short Description** 
Errors when initiating the plugin

**Actual Behavior** 
When I navigate to a page on any site and open the plugin I get an error that says `Cannot establish connection on this page**

**Expected Behavior** 
Not get an error

**To Reproduce** 
Navigate to a page on any site and open the plugin I get an error that says `Cannot establish connection on this page*

![Screenshot 2024-12-20 at 10 21 47 AM](https://github.com/user-attachments/assets/ad019e8e-3a9e-48f5-9e09-30b66d6c0bf8)

**Additional context** 
I may just be missing something but I get the errors immediately. Also when I go to the Chrome extension manager I shows this.

![Screenshot 2024-12-20 at 10 20 43 AM](https://github.com/user-attachments/assets/e05a2ec4-04d4-4ce9-b2d9-55262b9674ba)

**Comment by cody-molisee** [comment]
@christoph-codes This was from the 5.x.x version of the extension. Chrome had made some breaking changes around service workers and scripts.

basically, chrome required that all scripts be explicitly declared. Since the scripts in this version are built with a dynamic hash there was no easy way to declare that script name in the manifest.

Fret not, v6.0.0 is out now and all is well. you can download/update via the latest release assets. Follow the wiki or the readme for installation.

**Comment by cmolisee** [comment]
I accidently responded to this not realizing I was on another account. answer is still the same. closing this
